# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "6-macosx-build" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/.cache/fyne-cross
        key: ${{ runner.os }}-${{ runner.arch }}-build-cache-${{ hashFiles('**/go.sum') }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24"

    - name: Build
      run: make macos

    - uses: actions/upload-artifact@v4
      with:
        name: educabiz-scraper-${{ matrix.os }}-${{ matrix.arch }}
        path: educabiz-scraper-${{ matrix.os }}

  build-ubuntu-windows:
    strategy:
      matrix:
        os: [linux, windows]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/.cache/fyne-cross
        key: ${{ runner.os }}-${{ runner.arch }}-build-cache-${{ hashFiles('**/go.sum') }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.24"

    - name: Build
      run: make ${{ matrix.os }}

    - uses: actions/upload-artifact@v4
      with:
        name: educabiz-scraper-${{ matrix.os }}-${{ runner.arch }}
        path: educabiz-scraper-${{ matrix.os }}
